import { initializeApp } from "firebase-admin/app";
import { setGlobalOptions } from "firebase-functions/v2";

initializeApp();
setGlobalOptions({ region: "us-central1", maxInstances: 10 });

// Misma superficie que producción (flygo-rd): desplegar siempre desde flygo_nuevo/functions
export * from "./wallet.js";
export * from "./boarding.js";
export * from "./multiparada.js";
export * from "./publish.js";
export * from "./viaje_create_cliente.js";
export * from "./finance.js";
export * from "./liquidacion_semanal.js";
export * from "./pool_finance.js";
export * from "./admin_release_gira.js";
export * from "./scheduled_pool_notify.js";
export * from "./scheduled_pool_departure_owner.js";
export * from "./scheduled_gira_cupos_client_reminders.js";
export * from "./scheduled_pool_reservations_cleanup.js";
export * from "./trip_rating.js";
export * from "./trip_feedback.js";
export * from "./cliente_fidelidad_stats.js";
export * from "./bola_pueblo.js";
export * from "./incidencias.js";
export * from "./reportes.js";
export * from "./alertas_admin.js";
export * from "./config_admin.js";
export * from "./recarga_admin.js";
export * from "./taxista_cola_promote.js";
export * from "./chat_push.js";
export * from "./rai_asistente.js";
export * from "./admin_dashboard.js";
export * from "./pool_share_preview.js";
export * from "./admin_reset_gira_abuso.js";
export * from "./taxista_documentos.js";
export * from "./taxista_historial.js";
export * from "./banco_movimientos.js";
export * from "./conciliacion.js";
export * from "./recaudo_qr.js";
export * from "./azul.js";
export * from "./corporativo_rutas.js";
export * from "./corporativo_billing.js";
export * from "./corporativo_admin.js";
export * from "./corporativo_feriados_rd.js";
export * from "./corporativo_notificaciones.js";
export * from "./corporativo_recogida_perdida.js";
export * from "./corporativo_chofer_confirmacion.js";
export * from "./corporativo_codigo_distribucion.js";
export * from "./corporativo_validacion.js";
export * from "./corporativo_codigo_vencimiento.js";
export * from "./corporativo_viajes_monitor.js";
export * from "./corporativo_abordaje.js";
export * from "./corporativo_codigo_viaje.js";
export * from "./places_proxy.js";
export * from "./turismo_asignacion.js";
export * from "./turismo_mensajes_adm_notify.js";
